services:
  redis:
    image: redis:7.4.2-alpine
    expose:
      - ${REDIS_PORT_INTERNAL}
    volumes:
      - redis-data:/data
    networks:
      - app-network

  backend:
    depends_on:
      - mongodb
      - redis
    expose:
      - ${BACKEND_PORT_INTERNAL}
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/code
      - /code/.venv
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - PROJECT_NAME=${PROJECT_NAME}
      - CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - DEBUG=${BACKEND_DEBUG}
      - DOMAIN=${DOMAIN}
      - ACCESS_TOKEN_EXPIRE_SECONDS=${ACCESS_TOKEN_EXPIRE_SECONDS}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - BACKEND_PORT_INTERNAL=${BACKEND_PORT_INTERNAL}
      - REDIS_PORT=${REDIS_PORT_INTERNAL}
      - REDIS_HOST=${REDIS_HOST}
      # PATHS
      - LOGIN_PATH=${LOGIN_PATH}
      - VERIFY_MAIL_PATH=${VERIFY_MAIL_PATH}
      - PASSWORD_RESET_PATH=${PASSWORD_RESET_PATH}
      - EXAM_INSTANCE_PATH=${EXAM_INSTANCE_PATH}
    networks:
      - app-network
    command: sh -c "uv run fastapi dev --port ${BACKEND_PORT_INTERNAL} --host 0.0.0.0 --reload --proxy-headers"

  celery_worker:
    depends_on:
      - backend
      - redis
    container_name: celery_worker
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uv run celery --app app.celery.worker worker --loglevel=info --uid=nobody  --gid=nogroup
    volumes:
      - ./backend/:/code
      - /code/.venv
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - PROJECT_NAME=${PROJECT_NAME}
      - CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - DEBUG=${BACKEND_DEBUG}
      - DOMAIN=${DOMAIN}
      - ACCESS_TOKEN_EXPIRE_SECONDS=${ACCESS_TOKEN_EXPIRE_SECONDS}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - BACKEND_PORT_INTERNAL=${BACKEND_PORT_INTERNAL}
      - REDIS_PORT=${REDIS_PORT_INTERNAL}
      - REDIS_HOST=${REDIS_HOST}
      # PATHS
      - LOGIN_PATH=${LOGIN_PATH}
      - VERIFY_MAIL_PATH=${VERIFY_MAIL_PATH}
      - PASSWORD_RESET_PATH=${PASSWORD_RESET_PATH}
      - EXAM_INSTANCE_PATH=${EXAM_INSTANCE_PATH}
    networks:
      - app-network

  flower:
    container_name: flower
    expose:
      - ${FLOWER_PORT_INTERNAL}
    environment:
      - CELERY_BROKER_URL=redis://redis:${REDIS_PORT_INTERNAL}/0
      - CELERY_RESULT_BACKEND=redis://redis:${REDIS_PORT_INTERNAL}/0
    depends_on:
      - celery_worker
      - redis
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uv run celery --broker=redis://redis:${REDIS_PORT_INTERNAL}/0 flower --port=${FLOWER_PORT_INTERNAL} --url-prefix=/dev/flower
    networks:
      - app-network

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - ${FRONTEND_PORT_INTERNAL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PORT=${FRONTEND_PORT_INTERNAL}
      - VERIFY_MAIL_PATH=${VERIFY_MAIL_PATH}
      - PASSWORD_RESET_PATH=${PASSWORD_RESET_PATH}
    networks:
      - app-network
    tty: true
    command: sh -c "npm run dev -- --host 0.0.0.0 --port ${FRONTEND_PORT_INTERNAL}"

  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi9
    ports:
      - ${MONGO_PORT}:${MONGO_PORT_INTERNAL}
    volumes:
      - db_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    networks:
      - app-network

  nginx:
    image: nginx:1.27.3-alpine-slim
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf.template
      - ./nginx/entrypoint.sh:/etc/nginx/entrypoint.sh
      - ./nginx/certs/:/etc/nginx/certs/
    environment:
      - BACKEND_PORT_INTERNAL=${BACKEND_PORT_INTERNAL}
      - FRONTEND_PORT_INTERNAL=${FRONTEND_PORT_INTERNAL}
      - DOMAIN=${DOMAIN}
      - MAILHOG_UI_PORT_INTERNAL=${MAILHOG_UI_PORT_INTERNAL}
      - FLOWER_PORT_INTERNAL=${FLOWER_PORT_INTERNAL}
    entrypoint: [ "/bin/sh", "/etc/nginx/entrypoint.sh" ]
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog:latest
    expose:
      - ${MAILHOG_UI_PORT_INTERNAL}
    ports:
      - ${MAILHOG_PORT}:${MAILHOG_PORT_INTERNAL}
    networks:
      - app-network


volumes:
  db_data:
  redis-data:

networks:
  app-network:
    driver: bridge